# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 197f4a49b898b8c54cf499a73d11a16ce3eaacafe948bcb9e96694850236c3464fa84b78696a659681ce2e723bb65ecaf9d73e4694c175f0665db260c0ff8d8b

test:
  secret_key_base: 1574801852f93292d364581374b496fdec96fec3884db688f1ae51d3435ef3b3371cb3db9ce1efb34b890df18251f6da6532dc5274e359273b7f36f3acd96a1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
